packages:
  - apps/web
  - packages/contracts
  - packages/ui

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

nodeVersion: 24.14.0
engineStrict: true

overrides:
  brace-expansion: 5.0.8
  fontless>esbuild: 0.28.1
  postcss@8.5.17: 8.5.18
  tar@7.5.20: 7.5.21

hoistPattern:
  - '*'
  - '!@esbuild/*'
