"""Generate deterministic JSON Schema artifacts from canonical models."""

import json
from pathlib import Path

from pydantic import BaseModel

from srbg_contracts.models import (
    ClaimConflict,
    ClaimConflictDecisionRequest,
    ClaimConflictDecisionResponse,
    ClaimView,
    ClusterCandidateView,
    ClusterDecisionRequest,
    CollectionCreateRequest,
    CollectionPatchRequest,
    CollectionSummary,
    ConfirmedFact,
    ConnectorConfigPreview,
    ConnectorConfigPreviewRequest,
    ConnectorConfigRequest,
    ConnectorConfigVersionView,
    ConnectorDefinitionView,
    CreateSourceRequest,
    CursorPage,
    DailyDraftRequest,
    DailyReport,
    DigitalCaseDetail,
    DigitalCaseReviewPatch,
    DiscoveryDailyUsageView,
    DiscoverySettingPatchRequest,
    DiscoverySettingView,
    DiscoveryTopicPatchRequest,
    DiscoveryTopicView,
    DocumentDetail,
    DocumentPageView,
    EventCandidateGenerationResponse,
    EventDetail,
    EventItem,
    EventRelationView,
    EventTimeline,
    EvidenceView,
    FeedbackRequest,
    FeedNotice,
    FeedPage,
    FetchScheduleUpdate,
    FetchScheduleView,
    FingerprintResponse,
    FixtureUploadResponse,
    GoldAnnotationRequest,
    GoldAnnotationView,
    GoldArbitrationPacket,
    GoldArbitrationRequest,
    GoldReleaseRequest,
    GoldReleaseView,
    GoldTaskCreateRequest,
    GoldTaskView,
    HotTopicPage,
    ItemDetail,
    ItemSummary,
    LivenessResponse,
    MeResponse,
    MetricSample,
    OperationsOverview,
    OperatorTaskCompleteRequest,
    OperatorTaskCreateRequest,
    OperatorTaskView,
    OperatorWorkSessionCorrectionRequest,
    OperatorWorkSessionHeartbeatRequest,
    OperatorWorkSessionStart,
    OperatorWorkSessionStopRequest,
    OperatorWorkSessionView,
    PaperDetail,
    PersonalSourceCreateRequest,
    PersonalSourcePatchRequest,
    PersonalSourceReprobeRequest,
    PersonalSourceStreamView,
    PersonalSourceView,
    PilotMetrics,
    PilotSourceResumeRequest,
    PilotWindowCompleteRequest,
    PilotWindowCreateRequest,
    PilotWindowStartRequest,
    PilotWindowView,
    ProblemDetails,
    ProductNormalizationCandidateView,
    ProductNormalizationDecisionRequest,
    PublicationRevisionRequest,
    PublicationWithdrawalRequest,
    PublishedEventDetailV1,
    PublishedEventSummaryV1,
    QualificationRunView,
    ReadinessResponse,
    ReplayRequest,
    ReplayResult,
    ReplayTaskView,
    ReviewCandidateDecisionRequest,
    ReviewDecisionRequest,
    ReviewDecisionResponse,
    ReviewTaskDetail,
    ReviewTaskSummary,
    SaveItemRequest,
    ScoreOverrideRequest,
    ScoreSummary,
    SearchContext,
    SourceActionRequest,
    SourceAssessmentSubmission,
    SourceAttentionPage,
    SourceAuditEventView,
    SourceAutoScoreDetailView,
    SourceAutoScoreSummaryView,
    SourceCandidateBatchDecisionRequest,
    SourceCandidateBatchDecisionResult,
    SourceCandidateCreateRequest,
    SourceCandidateDecisionRequest,
    SourceCandidateDecisionResult,
    SourceCandidateDetail,
    SourceCandidatePage,
    SourceCandidateQualificationRequest,
    SourceComparison,
    SourceCoverageMatrix,
    SourceDetail,
    SourceGovernanceMetadataUpdate,
    SourceHealthView,
    SourceLifecycleActionRequest,
    SourceLifecycleEventView,
    SourceOnboardingSubmission,
    SourcePolicyDecisionRequest,
    SourcePolicySubmission,
    SourcePolicyV2Submission,
    SourcePolicyVersionView,
    SourceProductionApprovalRequest,
    SourceProfileModelOutput,
    SourceProfileOverrideRequest,
    SourceProfileView,
    SourceStreamPage,
    SourceSummary,
    SourceTransitionRequest,
    SourceTrialQualitySummary,
    SourceTrialRunRequest,
    SourceTrialRunView,
    StreamProbeRunView,
    TechnologyProductDetail,
    TypeSummary,
    UnverifiedFact,
    VersionChangeEscalationRequest,
    VersionDiffResponse,
    VersionResponse,
    VersionTimelineResponse,
)

SCHEMA_MODELS: dict[str, type[BaseModel]] = {
    "feedback-request.schema.json": FeedbackRequest,
    "metric-sample.schema.json": MetricSample,
    "operations-overview.schema.json": OperationsOverview,
    "pilot-metrics.schema.json": PilotMetrics,
    "pilot-source-resume-request.schema.json": PilotSourceResumeRequest,
    "pilot-window-complete-request.schema.json": PilotWindowCompleteRequest,
    "pilot-window-create-request.schema.json": PilotWindowCreateRequest,
    "pilot-window-start-request.schema.json": PilotWindowStartRequest,
    "pilot-window-view.schema.json": PilotWindowView,
    "operator-task-create-request.schema.json": OperatorTaskCreateRequest,
    "personal-source-patch-request.schema.json": PersonalSourcePatchRequest,
    "personal-source-create-request.schema.json": PersonalSourceCreateRequest,
    "personal-source-reprobe-request.schema.json": PersonalSourceReprobeRequest,
    "personal-source-stream-view.schema.json": PersonalSourceStreamView,
    "stream-probe-run-view.schema.json": StreamProbeRunView,
    "personal-source-view.schema.json": PersonalSourceView,
    "discovery-setting-patch-request.schema.json": DiscoverySettingPatchRequest,
    "discovery-setting-view.schema.json": DiscoverySettingView,
    "discovery-topic-patch-request.schema.json": DiscoveryTopicPatchRequest,
    "discovery-topic-view.schema.json": DiscoveryTopicView,
    "discovery-daily-usage-view.schema.json": DiscoveryDailyUsageView,
    "source-auto-score-summary-view.schema.json": SourceAutoScoreSummaryView,
    "source-auto-score-detail-view.schema.json": SourceAutoScoreDetailView,
    "source-profile-model-output.schema.json": SourceProfileModelOutput,
    "source-profile-override-request.schema.json": SourceProfileOverrideRequest,
    "source-profile-view.schema.json": SourceProfileView,
    "operator-task-complete-request.schema.json": OperatorTaskCompleteRequest,
    "operator-task-view.schema.json": OperatorTaskView,
    "operator-work-session-start.schema.json": OperatorWorkSessionStart,
    "operator-work-session-heartbeat-request.schema.json": OperatorWorkSessionHeartbeatRequest,
    "operator-work-session-stop-request.schema.json": OperatorWorkSessionStopRequest,
    "operator-work-session-correction-request.schema.json": OperatorWorkSessionCorrectionRequest,
    "operator-work-session-view.schema.json": OperatorWorkSessionView,
    "gold-task-create-request.schema.json": GoldTaskCreateRequest,
    "gold-task-view.schema.json": GoldTaskView,
    "gold-annotation-request.schema.json": GoldAnnotationRequest,
    "gold-annotation-view.schema.json": GoldAnnotationView,
    "gold-arbitration-packet.schema.json": GoldArbitrationPacket,
    "gold-arbitration-request.schema.json": GoldArbitrationRequest,
    "gold-release-request.schema.json": GoldReleaseRequest,
    "gold-release-view.schema.json": GoldReleaseView,
    "replay-request.schema.json": ReplayRequest,
    "replay-result.schema.json": ReplayResult,
    "replay-task-view.schema.json": ReplayTaskView,
    "fetch-schedule-update.schema.json": FetchScheduleUpdate,
    "fetch-schedule-view.schema.json": FetchScheduleView,
    "source-health-view.schema.json": SourceHealthView,
    "collection-create-request.schema.json": CollectionCreateRequest,
    "collection-patch-request.schema.json": CollectionPatchRequest,
    "collection-summary.schema.json": CollectionSummary,
    "connector-config-preview.schema.json": ConnectorConfigPreview,
    "connector-config-preview-request.schema.json": ConnectorConfigPreviewRequest,
    "connector-config-request.schema.json": ConnectorConfigRequest,
    "connector-config-version.schema.json": ConnectorConfigVersionView,
    "connector-definition.schema.json": ConnectorDefinitionView,
    "cursor-page.schema.json": CursorPage[dict[str, str | int | bool | None]],
    "digital-case-detail.schema.json": DigitalCaseDetail,
    "digital-case-review-patch.schema.json": DigitalCaseReviewPatch,
    "daily-draft-request.schema.json": DailyDraftRequest,
    "daily-report.schema.json": DailyReport,
    "paper-detail.schema.json": PaperDetail,
    "technology-product-detail.schema.json": TechnologyProductDetail,
    "create-source-request.schema.json": CreateSourceRequest,
    "source-assessment-submission.schema.json": SourceAssessmentSubmission,
    "source-governance-metadata-update.schema.json": SourceGovernanceMetadataUpdate,
    "claim-view.schema.json": ClaimView,
    "claim-conflict.schema.json": ClaimConflict,
    "claim-conflict-decision-request.schema.json": ClaimConflictDecisionRequest,
    "claim-conflict-decision-response.schema.json": ClaimConflictDecisionResponse,
    "confirmed-fact.schema.json": ConfirmedFact,
    "document-detail.schema.json": DocumentDetail,
    "document-page-view.schema.json": DocumentPageView,
    "feed-notice.schema.json": FeedNotice,
    "feed-page.schema.json": FeedPage,
    "fingerprint-response.schema.json": FingerprintResponse,
    "hot-topic-page.schema.json": HotTopicPage,
    "evidence-view.schema.json": EvidenceView,
    "event-candidate-generation-response.schema.json": EventCandidateGenerationResponse,
    "event-detail.schema.json": EventDetail,
    "cluster-candidate-view.schema.json": ClusterCandidateView,
    "cluster-decision-request.schema.json": ClusterDecisionRequest,
    "event-item.schema.json": EventItem,
    "event-relation-view.schema.json": EventRelationView,
    "event-timeline.schema.json": EventTimeline,
    "fixture-upload-response.schema.json": FixtureUploadResponse,
    "liveness-response.schema.json": LivenessResponse,
    "item-summary.schema.json": ItemSummary,
    "item-detail.schema.json": ItemDetail,
    "me-response.schema.json": MeResponse,
    "problem-details.schema.json": ProblemDetails,
    "product-normalization-candidate.schema.json": ProductNormalizationCandidateView,
    "product-normalization-decision-request.schema.json": ProductNormalizationDecisionRequest,
    "publication-revision-request.schema.json": PublicationRevisionRequest,
    "publication-withdrawal-request.schema.json": PublicationWithdrawalRequest,
    "published-event-summary-v1.schema.json": PublishedEventSummaryV1,
    "published-event-detail-v1.schema.json": PublishedEventDetailV1,
    "score-override-request.schema.json": ScoreOverrideRequest,
    "score-summary.schema.json": ScoreSummary,
    "save-item-request.schema.json": SaveItemRequest,
    "search-context.schema.json": SearchContext,
    "readiness-response.schema.json": ReadinessResponse,
    "review-decision-request.schema.json": ReviewDecisionRequest,
    "review-decision-response.schema.json": ReviewDecisionResponse,
    "review-candidate-decision-request.schema.json": ReviewCandidateDecisionRequest,
    "review-task-detail.schema.json": ReviewTaskDetail,
    "review-task-summary.schema.json": ReviewTaskSummary,
    "source-action-request.schema.json": SourceActionRequest,
    "source-attention-page.schema.json": SourceAttentionPage,
    "source-audit-event.schema.json": SourceAuditEventView,
    "source-candidate-batch-decision-request.schema.json": SourceCandidateBatchDecisionRequest,
    "source-candidate-batch-decision-result.schema.json": SourceCandidateBatchDecisionResult,
    "source-candidate-create-request.schema.json": SourceCandidateCreateRequest,
    "source-candidate-decision-request.schema.json": SourceCandidateDecisionRequest,
    "source-candidate-decision-result.schema.json": SourceCandidateDecisionResult,
    "source-candidate-detail.schema.json": SourceCandidateDetail,
    "source-candidate-page.schema.json": SourceCandidatePage,
    "source-candidate-qualification-request.schema.json": SourceCandidateQualificationRequest,
    "source-comparison.schema.json": SourceComparison,
    "source-coverage-matrix.schema.json": SourceCoverageMatrix,
    "source-detail.schema.json": SourceDetail,
    "source-lifecycle-action-request.schema.json": SourceLifecycleActionRequest,
    "source-lifecycle-event.schema.json": SourceLifecycleEventView,
    "source-onboarding-submission.schema.json": SourceOnboardingSubmission,
    "source-policy-decision-request.schema.json": SourcePolicyDecisionRequest,
    "source-policy-submission.schema.json": SourcePolicySubmission,
    "source-policy-v2-submission.schema.json": SourcePolicyV2Submission,
    "source-policy-version.schema.json": SourcePolicyVersionView,
    "source-production-approval-request.schema.json": SourceProductionApprovalRequest,
    "source-summary.schema.json": SourceSummary,
    "source-stream-page.schema.json": SourceStreamPage,
    "source-trial-run-request.schema.json": SourceTrialRunRequest,
    "source-trial-quality-summary.schema.json": SourceTrialQualitySummary,
    "source-trial-run.schema.json": SourceTrialRunView,
    "source-transition-request.schema.json": SourceTransitionRequest,
    "type-summary.schema.json": TypeSummary,
    "unverified-fact.schema.json": UnverifiedFact,
    "version-diff-response.schema.json": VersionDiffResponse,
    "version-change-escalation-request.schema.json": VersionChangeEscalationRequest,
    "version-response.schema.json": VersionResponse,
    "version-timeline-response.schema.json": VersionTimelineResponse,
    "qualification-run.schema.json": QualificationRunView,
}


def render_schemas() -> dict[str, str]:
    return {
        filename: json.dumps(
            model.model_json_schema(), ensure_ascii=False, indent=2, sort_keys=True
        )
        + "\n"
        for filename, model in SCHEMA_MODELS.items()
    }


def write_schemas(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in render_schemas().items():
        (output_dir / filename).write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    repository_root = Path(__file__).resolve().parents[4]
    write_schemas(repository_root / "packages/contracts/generated/json-schema")


if __name__ == "__main__":
    main()
