FROM pgvector/pgvector:0.8.2-pg17-bookworm AS pgvector

FROM postgres:17.10-bookworm

COPY --from=pgvector /usr/lib/postgresql/17/lib/vector.so /usr/lib/postgresql/17/lib/vector.so
COPY --from=pgvector /usr/share/postgresql/17/extension/vector* /usr/share/postgresql/17/extension/

USER postgres
